name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ '*' ]

env:
  CARGO_TERM_COLOR: always
  GROONGA_VERSION: 12.0.8

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt update
        sudo apt install -y wget tar pkg-config clang-14 build-essential zlib1g zlib1g-dev liblz4-1 liblz4-dev libzstd1 libzstd-dev libmpack0 libmsgpack-dev libzmq5 libzmq3-dev libevent-dev libmecab-dev
    - name: Install Groonga (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        cd "`mktemp -d`"
        wget https://packages.groonga.org/source/groonga/groonga-${GROONGA_VERSION}.tar.gz
        tar zxf groonga-${GROONGA_VERSION}.tar.gz
        cd groonga-${GROONGA_VERSION}
        ./configure --with-zlib --with-lz4 --with-zstd
        make -j$(grep '^processor' /proc/cpuinfo | wc -l)
        sudo make install
        sudo ldconfig
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
